-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 14:43:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BASETESTESRV_murilo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BASETESTESRV_murilo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BASETESTESRV_murilo` DEFAULT CHARACTER SET utf8 ;
USE `BASETESTESRV_murilo` ;

-- -----------------------------------------------------
-- Table `BASETESTESRV_murilo`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASETESTESRV_murilo`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(255) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BASETESTESRV_murilo`.`Carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASETESTESRV_murilo`.`Carros` (
  `idCarros` INT NOT NULL AUTO_INCREMENT,
  `Fabricante` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCarros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BASETESTESRV_murilo`.`Vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASETESTESRV_murilo`.`Vagas` (
  `idVagas` INT NOT NULL AUTO_INCREMENT,
  `Local` VARCHAR(45) NOT NULL,
  `Valor` FLOAT NOT NULL,
  PRIMARY KEY (`idVagas`),
  UNIQUE INDEX `Local_UNIQUE` (`Local` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BASETESTESRV_murilo`.`Estacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BASETESTESRV_murilo`.`Estacionamento` (
  `idEstacionamento` INT NOT NULL AUTO_INCREMENT,
  `Clientes_idClientes` INT NOT NULL,
  `Carros_idCarros` INT NOT NULL,
  `Vagas_idVagas` INT NOT NULL,
  `data_entrada` TIMESTAMP NULL,
  `data_saida` TIMESTAMP NULL,
  PRIMARY KEY (`idEstacionamento`, `Clientes_idClientes`, `Carros_idCarros`, `Vagas_idVagas`),
  INDEX `fk_Estacionamento_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Estacionamento_Carros1_idx` (`Carros_idCarros` ASC) VISIBLE,
  INDEX `fk_Estacionamento_Vagas1_idx` (`Vagas_idVagas` ASC) VISIBLE,
  CONSTRAINT `fk_Estacionamento_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `BASETESTESRV_murilo`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estacionamento_Carros1`
    FOREIGN KEY (`Carros_idCarros`)
    REFERENCES `BASETESTESRV_murilo`.`Carros` (`idCarros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estacionamento_Vagas1`
    FOREIGN KEY (`Vagas_idVagas`)
    REFERENCES `BASETESTESRV_murilo`.`Vagas` (`idVagas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
